# Generated by Django 4.1.6 on 2023-03-06 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('floor', models.PositiveIntegerField(default='0')),
                ('description', models.CharField(blank=True, max_length=250)),
                ('capacity', models.PositiveIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('start_date', models.DateField()),
                ('time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('type_of_event', models.CharField(choices=[('LECTURE', 'Lecture'), ('LAB', 'Lab'), ('LANG CLASS', 'Language Class'), ('DI', 'Drop In'), ('EC', 'Example Class')], default='LECTURE', max_length=20)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='floors.room')),
            ],
        ),
    ]
