# Generated by Django 4.1.6 on 2023-03-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floors', '0002_alter_event_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Lecture Theatre', 'Lecture Theatre'), ('Collab Space', 'Collab Space'), ('Research Lab', 'Research Lab'), ('Computer Lab', 'Computer Lab'), ('Office', 'Office'), ('Help Desk', 'Help Desk'), ('Meeting Room', 'Meeting Room'), ('Teaching', 'Teaching'), ('PGR Home', 'PGR Home'), ('PGR Lab', 'PGR Lab')], default='Office', max_length=40),
        ),
        migrations.AlterField(
            model_name='event',
            name='type_of_event',
            field=models.CharField(choices=[('Lecture', 'Lecture'), ('Lab', 'Lab'), ('Language Class', 'Language Class'), ('Drop In', 'Drop In'), ('Example Class', 'Example Class')], default='Lecture', max_length=20),
        ),
    ]
