# Generated by Django 4.1.6 on 2023-03-23 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floors', '0004_alter_room_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturer', models.CharField(default='', max_length=250)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='floors.room')),
            ],
        ),
    ]
