# Generated by Django 4.1.6 on 2023-03-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floors', '0005_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='lecturer',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
