# Generated by Django 4.1.6 on 2023-03-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floors', '0006_alter_office_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='presenter',
            field=models.CharField(default='', max_length=250),
        ),
    ]
